### PR TITLE
Re-add Profiler

### PR DESCRIPTION
**Pull request by gauravarya272**
Original PR: https://github.com/battlecode/battlecode21/pull/257

### CODE REVIEW

**Comment by gauravarya272** [comment]
The client code looks okay to me. @j-mao @wflms20110333 could you take a look at the engine changes?

**Comment by gauravarya272** [comment]
The client code looks okay, @j-mao @wflms20110333 could you take a look at the engine code?

**Comment by arvid220u** [comment]
the reason it was removed was because it made the client less responsive (and it was already kinda bad last year). if this year's game is less memory intensive, then I think it's fine to merge!

another option would be to create a switch somewhere like "enable profiler", so that it can be turned off if it gets unresponsive

**Comment by gauravarya272** [comment]
That makes sense. Unfortunately, I think games this year tend to have more units and actions than last year :/ I've added a shortcut to turn off profiling of matches while they're being played back. My thinking is that it doesn't make anything worse since it can always be disabled, and it could be useful for competitors in certain situations like testing on a small map?

**Comment by jmerle** [comment]
The primary reasons why the bc20 client became less responsive when the profiler was used should be fixed this year:
1. In the bc20 client we loaded all profiling data for a team into the profiler's iframe every time a match was loaded or the user selected a different robot to display in the profiler tab's sidebar. This caused a lot of traffic between the client's renderer process and the iframe, and caused hundreds of megabytes of data to be processed every time a new robot was selected. This is now fixed by doing most of the processing up front once and only transmitting the data speedscope needs to display (instead of all data of team), which makes it a lot more responsive (~0.5-1 seconds of delay when switching between robots instead of ~3-10 seconds).
2. In bc20 the profiler did not have a cap on the amount of events it would record. This sometimes lead to 10GB+ replay files, which would understandably cause problems in the client. This is now fixed by capping the amount of recorded events at 10M events per team per match, which means there is at most roughly 250MB worth of profiling data in a replay file.

**Comment by j-mao** [comment]
I'd be ok with merging if @gauravarya272 thinks the client-side code is ok and @wflms20110333 thinks the engine-side code is ok. @arvid220u does the above discussion sound good to you?

**Comment by arvid220u** [comment]
yep this sounds good to me, i like the switch to turn profiling on/off

**Review by j-mao — APPROVED** [review]
The engine side of this seems ok. @gauravarya272 I'll leave you to review the client. Be aware that this affects the schema.

**Pull request merged**
