### PR TITLE
Online client

### PR DESCRIPTION
**Pull request by gauravarya272**

### CODE REVIEW

**Comment by arvid220u** [comment]
generally looks good to me, but this looks like the release script for battlehack? (it has pypi things...) is this actually the script you run to release things? @gauravarya272 @n8kim1 @j-mao 

i would suggest copying the release.py from battlecode20 but i'm not sure if there is a different release procedure this year

**Comment by j-mao** [comment]
agree that the release script does look out of date (battlehack 2020 was in python, and this script involves publishing the engine to a python pypi repository).

unclear on what the full release procedure is, as I'm not fully involved with web/infra this year - I've manually poked frontend releases with `frontend/deploy.sh`, likely there should be other things involved though.

@n8kim1 @tmightyquinn what do you think?

**Comment by n8kim1** [comment]
yeah, quinn and i talked a bit abt this, should've written it down somehwere haha
release.py is the battlehack release script. it's nearly entirely obsolete, I plan on adding some comments and keeping it around
the frontend release is done w `frontend/deploy.sh` with some extra steps too. I'll prob add client() to there

**Comment by n8kim1** [comment]
@arvid220u @Diuven @j-mao could someone look over this?

**Review by j-mao — APPROVED** [review]
`THIS_URL` looks unnecessary, but I don't see anything suspicious

**Pull request merged**
