### PR TITLE
Visualizer Improvements

### PR DESCRIPTION
**Pull request by StoneT2000**
Addresses some things the community was asking for:
1. Indication of conviction amount in units, now shown through darker to lighter shade, and smaller to bigger sized units visually
2. Income per turn and a income graph over time to show "eco dominance" or something (cool to analyze and shows a clearer indication of the economy of a team)

Screen Shot 2021-01-25 at 3 50 31 PM

### CODE REVIEW

**Comment by gauravarya272** [comment]
Darn, I just saw this. Thanks for the PR! The graph/new tracking kills my computer at the moment unfortunately, let me see if I can speed it up before quals

**Comment by StoneT2000** [comment]
@gauravarya272 The main issue might be the graph sorting wihch is used to deal with the graph looking weird when we go from round `k` to round `k-n` for some n, k > 0. Couldn't figure out a way to keep it all nicely sorted.

**Comment by StoneT2000** [comment]
If there's not a better way, I think most competitors would at least want to see the total income value if the graph can't be shown (which I dont think is hard on the computer)

**Comment by gauravarya272** [comment]
Weirdly, it was actually the ctx.filter that was slowing stuff down.

**Comment by StoneT2000** [comment]
oh hm, maybe brightness filtering on 100s of units isnt fast. I think without that shading change it would still look good anyway, thanks!

**Comment by gauravarya272** [comment]
I've "merged" your changes into the client branch in a terrible way, sorry about that :) Take a look at https://github.com/battlecode/battlecode21/commit/ed975dc919bca64ac34c43b4a75207b785683e14 -- if it looks good to you and I haven't butchered anything, I'll merge it in for quals :)

**Comment by StoneT2000** [comment]
> I've "merged" your changes into the client branch in a terrible way, sorry about that :) Take a look at [ed975dc](https://github.com/battlecode/battlecode21/commit/ed975dc919bca64ac34c43b4a75207b785683e14) -- if it looks good to you and I haven't butchered anything, I'll merge it in for quals :)
> 
> In the meantime, I'll actually merge this properly -- but just take a look at that to make sure it's all right please!

Looks great! i did end up using a `//@ts-ignore` hope that's alright 😓

**Pull request merged**
